
client : appliclientChif.c serveur
	gcc -Wall appliclientChif.c -o client

serveur : appliserveurChif.c 
	gcc -Wall appliserveurChif.c -o serveur



all: 	client
	serveur

clean :
	rm -f client
	rm -f serveur
